<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { createItem, deleteItem, listItems, type Item } from '@/services/items'

const items = ref<Item[]>([])
const loading = ref(false)
const saving = ref(false)
const deletingId = ref<number | null>(null)
const error = ref<string | null>(null)
const title = ref('')
const description = ref('')
const completed = ref(false)

const completedCount = computed(() => items.value.filter((item) => item.completed).length)

onMounted(() => {
  void loadItems()
})

async function loadItems() {
  loading.value = true
  error.value = null

  try {
    items.value = await listItems()
  } catch (source) {
    error.value = messageFromError(source, 'Unable to load items')
  } finally {
    loading.value = false
  }
}

async function submitItem() {
  const trimmedTitle = title.value.trim()
  if (!trimmedTitle) {
    error.value = 'Title is required'
    return
  }

  saving.value = true
  error.value = null

  try {
    const item = await createItem({
      title: trimmedTitle,
      description: description.value.trim(),
      completed: completed.value,
    })
    items.value = [item, ...items.value]
    title.value = ''
    description.value = ''
    completed.value = false
  } catch (source) {
    error.value = messageFromError(source, 'Unable to create item')
  } finally {
    saving.value = false
  }
}

async function removeItem(item: Item) {
  deletingId.value = item.id
  error.value = null

  try {
    await deleteItem(item.id)
    items.value = items.value.filter((current) => current.id !== item.id)
  } catch (source) {
    error.value = messageFromError(source, 'Unable to delete item')
  } finally {
    deletingId.value = null
  }
}

function formatTimestamp(value: number): string {
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date(value))
}

function messageFromError(source: unknown, fallback: string): string {
  return source instanceof Error ? source.message : fallback
}
</script>

<template>
  <main class="app-page">
    <div class="page-shell">
      <section class="page-header">
        <div>
          <p class="eyebrow">Example resource</p>
          <h1>Items</h1>
          <p class="page-description">
            Manage task-like records through the Rust API and Diesel-backed persistence.
          </p>
        </div>

        <button class="secondary-button" type="button" :disabled="loading" @click="loadItems">
          {{ loading ? 'Refreshing' : 'Refresh' }}
        </button>
      </section>

      <section class="data-panel" aria-labelledby="new-item-title">
        <div class="section-heading">
          <h2 id="new-item-title">Create item</h2>
          <p>IDs and timestamps are generated by the backend service.</p>
        </div>

        <form class="resource-form" @submit.prevent="submitItem">
          <label class="form-field">
            <span>Title</span>
            <input v-model="title" class="text-input" autocomplete="off" placeholder="Ship API docs" />
          </label>

          <label class="form-field form-field--wide">
            <span>Description</span>
            <textarea
              v-model="description"
              class="text-area"
              rows="3"
              placeholder="Short operational note"
            />
          </label>

          <button
            class="toggle-button"
            type="button"
            role="switch"
            :aria-checked="completed"
            :class="{ 'toggle-button--on': completed }"
            @click="completed = !completed"
          >
            <span class="toggle-indicator" />
            <span>{{ completed ? 'Completed' : 'Open' }}</span>
          </button>

          <button class="primary-button" type="submit" :disabled="saving">
            {{ saving ? 'Creating' : 'Create item' }}
          </button>
        </form>
      </section>

      <p v-if="error" class="feedback feedback--error">{{ error }}</p>

      <section class="data-panel" aria-labelledby="items-list-title">
        <div class="section-heading section-heading--split">
          <div>
            <h2 id="items-list-title">Item list</h2>
            <p>{{ items.length }} total, {{ completedCount }} completed</p>
          </div>
        </div>

        <div v-if="loading" class="empty-state">Loading items</div>
        <div v-else-if="items.length === 0" class="empty-state">No items yet</div>

        <template v-else>
          <div class="table-wrapper">
            <table class="resource-table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Status</th>
                  <th>Created</th>
                  <th class="action-column">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in items" :key="item.id">
                  <td>
                    <div class="primary-cell">{{ item.title }}</div>
                    <div class="secondary-cell">{{ item.description || 'No description' }}</div>
                  </td>
                  <td>
                    <span class="status-badge">{{ item.completed ? 'completed' : 'open' }}</span>
                  </td>
                  <td class="mono-cell">{{ formatTimestamp(item.created_at) }}</td>
                  <td class="action-column">
                    <button
                      class="danger-button"
                      type="button"
                      :disabled="deletingId === item.id"
                      @click="removeItem(item)"
                    >
                      {{ deletingId === item.id ? 'Deleting' : 'Delete' }}
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div class="mobile-record-list">
            <article v-for="item in items" :key="item.id" class="record-card">
              <div class="record-card__header">
                <h3>{{ item.title }}</h3>
                <span class="status-badge">{{ item.completed ? 'completed' : 'open' }}</span>
              </div>
              <p>{{ item.description || 'No description' }}</p>
              <div class="record-card__footer">
                <span>{{ formatTimestamp(item.created_at) }}</span>
                <button
                  class="danger-button"
                  type="button"
                  :disabled="deletingId === item.id"
                  @click="removeItem(item)"
                >
                  {{ deletingId === item.id ? 'Deleting' : 'Delete' }}
                </button>
              </div>
            </article>
          </div>
        </template>
      </section>
    </div>
  </main>
</template>
