// @generated by Diesel CLI. Kept in source so the template works without Diesel CLI.

diesel::table! {
    use diesel::sql_types::{Bool, Int8, Text};

    items (id) {
        id -> Int8,
        title -> Text,
        description -> Text,
        completed -> Bool,
        created_at -> Int8,
        updated_at -> Int8,
    }
}

diesel::table! {
    use diesel::sql_types::{Bool, Int8, Text};

    users (id) {
        id -> Int8,
        name -> Text,
        email -> Text,
        active -> Bool,
        created_at -> Int8,
        updated_at -> Int8,
    }
}
