// @generated by Diesel CLI. Kept in source so the project builds without Diesel CLI.

diesel::table! {
    use diesel::sql_types::{BigInt, Bool, Text};

    items (id) {
        id -> BigInt,
        title -> Text,
        description -> Text,
        completed -> Bool,
        created_at -> BigInt,
        updated_at -> BigInt,
    }
}

diesel::table! {
    use diesel::sql_types::{BigInt, Bool, Text};

    users (id) {
        id -> BigInt,
        name -> Text,
        email -> Text,
        active -> Bool,
        created_at -> BigInt,
        updated_at -> BigInt,
    }
}
